### PR TITLE
Create advanced example for creating a PR after conversion

### PR DESCRIPTION
**Pull request by abelsiqueira**
**Description**

Create a new advanced example converting `CITATION.cff` to `.zenodo.json` and creating a Pull Request.

**Related issues**:
- #46 

**Instructions to review the pull request**

Review online and see example in this repo: https://github.com/abelsiqueira/python-template-test/pull/6

### CODE REVIEW

**Review by jspaaks — APPROVED** [review]
Nice work. I'm wondering if perhaps this PR's example should replace the "Create and push" example, since the existing example potentially throws away data in the `.zenodo.json`, this one makes a PR so users can see its proposed changes first.

**Comment by abelsiqueira** [comment]
I like the PR better, but @fdiblen mentioned that other users prefer pushing directly.

**Comment by jspaaks** [comment]
OK, let's just merge this one then

**Comment by abelsiqueira** [comment]
Thanks for the review.

**Pull request merged**
